agenda/urls.py
from django.urls import path
from agenda import views

app_name = 'agenda'
urlpatterns = [
    path('',views.index, name = 'index'),
    path('search/', views.search, name = 'search'),
    #CRUD
    path('contact/<int:contact_id>/detail/', views.contact, name = 'contact'),
    path('contact/create/', views.create, name = 'create'),
    path('contact/<int:contact_id>/update/', views.update, name = 'update'),
    path('contact/<int:contact_id>/delete/', views.delete, name = 'delete'),
   
   #USER
    path('user/create/', views.register, name = 'register'),
    path('user/login/', views.login_view, name = 'login'),
    path('user/logout/', views.logout_view, name = 'logout'),
    path('user/update/', views.user_update, name = 'user_update'),

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('agenda.urls') )
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

agenda/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
class Category(models.Model):
    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    name = models.CharField(max_length = 50)
    def __str__(self) -> str:
        return f'{self.name}'

# Create your models here.
class Contact(models.Model):
    first_name = models.CharField(max_length = 30)
    last_name = models.CharField(max_length = 30)
    phone = models.CharField(max_length = 20)
    email = models.EmailField(max_length = 100)
    created_date = models.DateTimeField(default = timezone.now)
    description = models.TextField(blank = True)
    show = models.BooleanField(default = True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category, 
        on_delete = models.SET_NULL,
        blank = True, null = True
        )
    owner = models.ForeignKey(
        User,
        on_delete = models.SET_NULL,
        blank = True, null = True)
    
    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'
    

agenda/forms.py
from agenda.models import Contact
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import password_validation
class ContactForm(forms.ModelForm):
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'accept':'image/*',
            }),
        required= False    )
    first_name = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class':'classe-a',
                'placeholder':'DIgite seu nome'
                }
            ), help_text='Insira seu primeiro nome'
        )
    
    last_name = forms.CharField(
        widget= forms.TextInput(
            attrs={ 'class':'class-b',
                    'placeholder':'Digite seu sobrenome'
            }
        ), help_text='Insira seu sobrenome'
    )
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
    class Meta:
        model = Contact
        fields = ('first_name','last_name', 'phone',
                  'email', 'description','category','picture',)
       
    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )
            self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        return super().clean()

    def clean_first_name(self):
        data = self.cleaned_data.get("first_name")
        if data == 'ABC':
            self.add_error('first_name' ,
                        ValidationError('Não digite ABC neste campo', 
                                        code='invalid'))
        return data
    
    def clean_last_name(self):
        cleaned_data = self.cleaned_data.get("last_name")
            
        if cleaned_data == 'DEF':
            self.add_error('last_name',
                            ValidationError('Não digite DEF neste campo', 
                                            code='invalid'))
        return cleaned_data

class RegisterForm(UserCreationForm):
    
    
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.CharField(
        required=True,
        min_length=3,
    )
    class Meta:
        model = User
        fields =(
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if User.objects.filter(email=email).exists():
            self.add_error(
                'email', ValidationError('Ja existe este e-mail', code = 'invalid')
            )
        return email
    

class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

agenda/views.py
from django.shortcuts import render

# Create your views here.
context = {}
def index(request):
    return render(request, 'agenda/index.html', context= context)

agenda/views/contact_forms.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from agenda.models import Contact
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from agenda.forms import ContactForm

@login_required(login_url='agenda:login')
def create(request):
    form_action = reverse("agenda:create")
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)
        context = {
            'form': form,
            'form_action':form_action
        }
        if form.is_valid():
            contact = form.save()
            messages.success('Usúario criado com sucesso')
            return redirect('agenda:update', contact_id=contact.pk )
        
        return render(request, 'agenda/create.html', context= context)
    
    form = ContactForm() 
    context = {
            'form': form,
            'form_action':form_action
        } 
    return render(request, 'agenda/create.html', context= context)

@login_required(login_url='agenda:login')
def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk = contact_id, show = True, owner = request.user
        )
    form_action = reverse("agenda:update", args=(contact_id,))
     
    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance = contact)
        
        context = {
            'form': form,
            'form_action':form_action
        }
        if form.is_valid():
            contact = form.save()
            messages.success('Usúario editado com sucesso')
            return redirect('agenda:update', contact_id = contact.pk )
        
        messages.warning('algo deu errado')
        return render(request, 'agenda/create.html', context= context)
    
    form = ContactForm(instance = contact) 
    context = {
            'form': form,
            'form_action':form_action
        }
    return render(request, 'agenda/create.html', context= context)
    
@login_required(login_url='agenda:login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk = contact_id, show = True, owner = request.user
        )
    confirmation = request.POST.get('confirmation', 'no')
    if confirmation =='yes':
        contact.delete()
        messages.warning('Usúario deletado')
        return redirect("agenda:index")
    
    return render(request, 
                  'agenda/contact.html',
                  {'contact':contact,
                   'confirmation' : confirmation})

agenda/views/contact_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
from agenda.models import Contact
from django.core.paginator import Paginator
# Create your views here.

def index(request):
    contacts = Contact.objects.filter(show=True).order_by('-id')
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj,
               'site_title':'contatos- '}
    return render(request, 'agenda/index.html', context= context)


def search(request):
    search = request.GET.get('q','').strip()
    if search == '':
        return redirect('agenda:index')
    contacts = Contact.objects\
                .filter(show=True)\
                .filter(Q(first_name__icontains=search) |
                        Q(last_name__icontains=search) |
                        Q(phone__icontains=search) |
                        Q(email__icontains=search))\
                .order_by('-id')
    
    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj,
               'site_title':'search- ',
               'search_value' : search}
    
    return render(request, 'agenda/index.html', context= context)
# Create your views here.
def contact(request, contact_id):
    contacts = get_object_or_404(Contact.objects, pk=contact_id,show = True)
    site_title = f'{contacts.first_name} {contacts.last_name} '
    context = {'contact':contacts,
               'site_title':site_title}
    print(context)
     
    return render(request, 'agenda/contact.html', context= context)

agenda/views/user_forms.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from agenda.forms import RegisterForm, RegisterUpdateForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
def register(request):
    form = RegisterForm(request.POST)

    if form.is_valid():
        contact = form.save(commit=False)
        contact.owner = request.user
        contact.save()
        messages.success(request, 'Usuário registrado')
        return redirect('agenda:login')
    
    return render(
        request, 'agenda/register.html',
        {
            'form':form
        }
    )
    

def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            messages.success(request, 'Logado com sucesso!')
            return redirect('agenda:index')
        messages.error(request, 'Login inválido')

    return render(
        request,
        'agenda/login.html',
        {
            'form': form
        }
    )
    
@login_required(login_url='agenda:login')
def logout_view(request):
    auth.logout(request)
    messages.success(request, "Usúario saiu")
    return redirect('agenda:login')

@login_required(login_url='agenda:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)
    if request.method != 'POST':
        return render(
            request,
            'agenda/register.html',
            {
                'form': form
            }
        )
    
    form = RegisterUpdateForm(data = request.POST, instance=request.user)
    if not form.is_valid():
        return render(
            request,
            'agenda/register.html',
            {
                'form': form
            }
        )
    form.save()
    messages.success(request, 'Usúario atualizado com sucesso')
    return redirect('agenda:index')

agenda/templates/agenda/contact.html
{% extends "global/base.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
            {{ contact.first_name }} {{ contact.last_name }}
        </h1>
        <p><b>ID:</b> {{contact.id}}</p>
        <p><b>E-Mail:</b> {{contact.email}}</p>
        <p><b>Phone:</b> {{contact.phone}}</p>
        <p><b>Created Date:</b> {{contact.created_date}}</p>
        <p><b>Descripition:</b> {{contact.description}}</p>
        <p><b>Category:</b> {{contact.category.name}}</p>
        {% if contact.picture %}
            <p>
                <img src="{{contact.picture.url}}" alt="{{ contact.first_name }} {{ contact.last_name }}">
            </p>
        {% endif %}
        {% if user == contact.owner %}
            <div class="contact-links">
                <a href="{% url "agenda:update" contact.id %}" class="btn btn-link">Update</a>
                <form action= "{% url "agenda:delete" contact.id%}" method = "POST">
                    {% csrf_token %}
                    {% if confirmation == 'no' %}
                        <input type="hidden" name = 'confirmation' value="yes">
                            <button class = "btn btn-link btn-delete" type = "submit"> Confirm? </button>
                        </input>
                        <button class = "btn btn-link btn-cancel" type = "submit">
                            <a href="{% url "agenda:index" %}"style="color:white;"> 
                                Cancel 
                            </a>
                        </button>  
                    {% else %}
                        <button class = "btn btn-link btn-delete" type = "submit"> Delete </button>
                    {% endif %}
                </form>
            </div>
        {% endif %}
    </div>
{% endblock content %}

agenda/templates/agenda/create.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Contact</h2>

    <form 
      action="{{form_action}}"
      method="POST"
      enctype="multipart/form-data"
      >
      {% csrf_token %}
      
      <div class="form-content">
        {% for field in form %}
        <div class="form-group">
          <label for="{{field.id_for_label}}">{{field.label}}</label>
            {{field}}
            {{field.errors}}
          {% if field.help_text %}
            <p class="help-text">{{field.help_text}}</p>
          {% endif %}
          {% if field.name == 'picture' and field.value.url%}
            <img src="{{field.value.url}}" alt="">
          {% endif %}
        </div>
        {% endfor %}
      </div>

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>

    </form>
  </div>
{% endblock content %}

agenda/templates/agenda/index.html
{% extends 'global/base.html' %}

{% block content %}
{% if page_obj %}
    <div class="responsive-table">
        <table class="contacts-table">
            <caption class = "table-caption">
                contacts
            </caption>
            <thead>
                <tr class="table-row table-row-header">
                    <th class="table-header">ID</th>
                    <th class="table-header">First Name</th>
                    <th class="table-header">Last Name</th>
                    <th class="table-header">Phone</th>
                    <th class="table-header">Email</th>
                </tr>
            </thead>
            <tbody>
                {% for contact in page_obj  %}
                <tr class="table-row">
                    <td class="table-cel">
                        <a href="{% url "agenda:contact" contact.id %}" /
                         class="table-link">{{contact.id}}</a>
                    </td>
                    <td class="table-cel">
                        <a href="{% url "agenda:contact" contact.id %}" /
                         class="table-link">{{contact.first_name}}</a>
                    </td>
                    <td class="table-cel">
                        <a href="{% url "agenda:contact" contact.id %}" /
                         class="table-link">{{contact.last_name}}</a>
                    </td>
                    <td class="table-cel">
                        <a href="{% url "agenda:contact" contact.id %}" /
                         class="table-link">{{contact.phone}}</a>
                    </td>
                    <td class="table-cel">
                        <a href="{% url "agenda:contact" contact.id %}" /
                         class="table-link">{{contact.email}}</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% else %}
<div class="single-contact">
    <h1 class="single-contact-name">
        Nada foi encontrado com sua busca atual:<br>"{{search_value}}"
    </h1>
    <h2>
        Refaça a busca
    </h2>        
{% endif %} 
{% endblock content %}

agenda/templates/agenda/login.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">
      <h2>Register</h2>
    {% if user.is_authenticated %}
    <p> você fez login como {{user.username}}.
        Clique <a href="{% url "agenda:logout" %}">aqui</a> para sair
    {% else %}    
        {% csrf_token %}  
        {% include "agenda/partials/user-form.html" %}
    {% endif %}
  </div>
{% endblock content %}

agenda/templates/agenda/register.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Register</h2>
    {% include "agenda/partials/user-form.html" %}

  </div>
{% endblock content %}